import '@vaa/styles/globals.scss';

import type { Metadata } from 'next';

import {
	mainThemes,
	themeDataKey,
} from '@vaa/components/theme-toggle/constants';
import { TRPCReactProvider } from '@vaa/trpc/react';
import { HydrateClient } from '@vaa/trpc/server';
import { ThemeProvider } from 'next-themes';
import { MedusaProvider } from 'src/hooks/medusa';
import {PropsWithChildren} from "react";

export const metadata: Metadata = {
	title: 'Create T3 App',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
	children,
}: Readonly<PropsWithChildren>) {
	return (
		<html lang="en" suppressHydrationWarning data-theme="light">
			<TRPCReactProvider>
				<body>
					<HydrateClient>
						<ThemeProvider themes={mainThemes} storageKey={themeDataKey}>
							<MedusaProvider>{children}</MedusaProvider>
						</ThemeProvider>
					</HydrateClient>
				</body>
			</TRPCReactProvider>
		</html>
	);
}
